### ISSUE TITLE
CSS variable support?

### ISSUE THREAD

**Issue by KTibow** [lesscpy/lesscpy#113]
Right now there's no way to use this with regular CSS variables without using a transpiler first. A way to support CSS variables would be nice.

**Comment by LouisNitag** [comment]
Any news on this issue? Even if Less adds support of variables, using native CSS variables makes easy the user-theming.

Eg.

```
/* theme.css */
body {
  --background: white;
  --text: white;
  --links: red;
}

/* style.less */
div {
  background: var(--background);
  color: var(--text);

  a {
    color: var(--links);
  }
}
```
