### ISSUE TITLE
Bump version number and release to PyPi

### ISSUE THREAD

**Issue by bbenne10** [lesscpy/lesscpy#50]
With the relatively recent introduction of `lesscpy.compile()`, I feel the version number should be bumped (probably `0.10.2` or even `0.11`, if there're other changes that could stand to be pushed as well). In the lastest code however, the version number is still `0.10.1`. This could lead to confusion with regard to what version `lesscpy.compile()` was included in (since that function is aguably a VERY useful one).

**Comment by saschpe** [comment]
Sorry folks for not responding earlier. @bbenne10 please do a pull request and I'll happily provide a new PyPI release.

**Comment by bbenne10** [comment]
Would you like it included in the PR for #51, or separate? Either works for me.

**Comment by saschpe** [comment]
I'll close this issue then and wait for your submit request(s). I can push another release afterwards.
