### ISSUE TITLE
Explicit typechecking against str

### ISSUE THREAD

**Issue by bbenne10** [lesscpy/lesscpy#51]
In python2.x, code should check against `basestring`. In 3.x, it should check against `str`. This is managed by the `six` library, which is meant to ease the transition between the two versions. There is currently broken code in about 5 files: 

* `lessc/parser.py`
* `lessc/scope.py`
* `lessc/color.py`
* `plib/call.py`
* `plib/expression.py`

In `lessc/scope.py`, there's a couple of comments that indicate that there's an attempt being made to make this library both python2 and python3 compatible. The comments seem to indicate that you should compare against `basestring` in py3 and `str` in py2. Not only could these comparisons be 
**GREATLY** simplified using `six`, but they are completely backwards. Py3 has no `basestring` and checking against `str` directly is dangerous in py2. I'm proposing adding a dependency upon `six` so that these problems can be transparently worked around without needing to resort to the `except NameError` check that is currently being done in `lessc/scope.py` (but nowhere else). I have forked the code and am working on integrating `six` where the explicit `str` checks are occuring. I will have a pull request before too long.

**Comment by bbenne10** [comment]
Would a pull request here get integrated? I'd be happy to create one.

**Comment by saschpe** [comment]
Sure!

**Comment by bbenne10** [comment]
My fork is a bit ahead of current development (or behind depending on your viewpoint), so this is less than trivial (i.e something I can do from home without the codebase cloned). I'll get on this first thing tomorrow and I'll have a PR before the end of day (~5EST)
