### ISSUE TITLE
Support for writing to file

### ISSUE THREAD

**Issue by ritave** [lesscpy/lesscpy#55]
When using standard lessc an output file argument can be given (```lessc asd.less asd.css```), I ask for support of this feature in this port.

**Comment by ritave** [comment]
Yeah, it's a shell feature (bash). We're running it from a program, without a shell - redirection doesn't work rhere

**Comment by bbenne10** [comment]
This shouldn't be hard to push into the run script. I'll see what I can do.

**Comment by ritave** [comment]
Wrong button pressed, sorry - mobile

**Comment by saschpe** [comment]
Should be closed with #60. Please give it a go and reopen if there's an issue. If it works for you I'll do another release.

**Comment by archangel-irk** [comment]
Please release new lesscpy with this feature.

**Comment by saschpe** [comment]
@archangel-irk Ok, done :-)

**Comment by archangel-irk** [comment]
@saschpe thanks.

**Comment by oulenz** [comment]
Would be useful if you could add this to the documentation --- I didn't realise I could specify the output file in a second positional argument. Thanks for implementing it!
