### ISSUE TITLE
nested @media queries sometimes loose outer scope

### ISSUE THREAD

**Issue by jecki** [lesscpy/lesscpy#61]
Minimal Example:

h1 { 
    &.title { 
    @media screen and (max-width: 460px) {
        background: url("image_460.jpg");  
    }  
    @media screen and (min-width: 461px) {
        background: url("image_740.jpg");  
    } 
    }  
}

yields:

@media screen and (min-width:461px) {
  background: url("image_740.jpg");
}
@media screen and (max-width:460px) {
  h1.title {
    background: url("image_460.jpg");
  }
}

In the first media-query block the outer scope h1.title was lost by lesscpy

It really should be:

@media screen and (max-width: 460px) {
  h1.title {
    background: url("image_460.jpg");
  }
}
@media screen and (min-width: 461px) {
  h1.title {
    background: url("image_740.jpg");
  }
}

**Comment by oliverpool** [comment]
I have the exact same issue : complex nested @media might result in a wrong CSS compilation
