### ISSUE TITLE
Bad version sequence

### ISSUE THREAD

**Issue by sambler** [lesscpy/lesscpy#94]
Back in Oct 2016 you increased the version to 0.12.0 in 56c16b809c48f2c and now in Dec 2017 you have gone back to 0.11.2 in 10919f6a9fe4151

I'm not sure why the earlier commit doesn't show in the master/lesscpy/init.py history but v0.12.0 was previously visible in pypi, now going back to 0.11.2 breaks packaging systems that had previously installed 0.12.0. Due to 0.12.0 no longer existing it leaves the current version as less than existing installed version.

**Comment by saschpe** [comment]
This is indeed annoying. Not sure what happened back then, but the best fix is to jump to 0.13.0.
